# Generated by Django 3.2 on 2022-08-05 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.TextField(default='Add message here'),
        ),
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(default='Add Blog title here', max_length=250, unique=True),
        ),
    ]
