# Generated by Django 3.2 on 2022-06-28 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_review_created_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
