# Generated by Django 3.2 on 2022-06-28 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
