# Generated by Django 3.2 on 2022-08-03 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20220802_1835'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
